serve-path: './subtitle-backup'
bind: 0.0.0.0
port: 3006
hidden:
  - '.DS_Store'

allow-all: false
allow-upload: false
allow-delete: false
allow-search: true
allow-symlink: false
allow-archive: false
enable-cors: true
render-index: true
render-try-index: true
render-spa: true
assets: ./dufs-assets/
compress: low